### ISSUE TITLE
The Enchanted Glade

### ISSUE THREAD

**Issue by suttoko** [alexqu0822/CodexLite#2]
when i get this quest, keep error
https://classic.wowhead.com/quest=937

1633x CodexLite\map.lua:716: attempt to call upvalue 'mm_check_func' (a nil value)
[string "@CodexLite\map.lua"]:716: in function <CodexLite\map.lua:702>
[string "@CodexLite\map.lua"]:914: in function <CodexLite\map.lua:875>

Locals:
map = 1438
num_changed = 0
meta = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
}
(for control) = <table> {
 1 = "unit"
 2 = 2021
 3 = <table> {
 }
 4 = <table> {
 }
}
uuid = <table> {
 1 = "unit"
 2 = 2021
 3 = <table> {
 }
 4 = <table> {
 }
}
data = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
color3 = <table> {
 1 = 0
 2 = 1
 3 = 0
}
coords = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
}
(for index) = 7
(for limit) = 13
(for step) = 1
index = 7
coord = <table> {
 1 = 34.100000
 2 = 29.900000
 3 = 1438
 4 = 300
 5 = <table> {
 }
}
val = <table> {
 1 = 2078.324974
 2 = 10816.518750
 3 = 1
 4 = 300
}
dx = 215.624901
dy = 152.418164
(*temporary) = nil
(*temporary) = 215.624901
(*temporary) = 152.418164
(*temporary) = 233.333333
(*temporary) = "attempt to call upvalue 'mm_check_func' (a nil value)"
__ns = <table> {
 __comm_obj_lookup = <table> {
 }
 __comm_meta = <table> {
 }
 __player_level = 11
 QUEST_GREETING = <function> defined @CodexLite\core.lua:1399
 __opt_log = <function> defined @CodexLite\init.lua:927
 __sv = <table> {
 }
 PLAYER_LEVEL_CHANGED = <function> defined @CodexLite\core.lua:1313
 QUEST_LOG_UPDATE = <function> defined @CodexLite\core.lua:1325
 _log_ = <function> defined @CodexLite\init.lua:873
 __rt = <table> {
 }
 GetColor3NextIndex = <function> defined @CodexLite\core.lua:165
 ____bn_tag = "xxxx#1234"
 DelUnit = <function> defined @CodexLite\core.lua:409
 QUEST_REMOVED = <function> defined @CodexLite\core.lua:1367
 _F_devDebugProfileTick = <function> defined @CodexLite\init.lua:48
 __map_meta = <table> {
 }
 MapDelVariedNodes = <function> defined @CodexLite\map.lua:1065
 QUEST_PROGRESS = <function> defined @CodexLite\core.lua:1423
 QUEST_COMPLETE = <function> defined @CodexLite\core.lua:1430
 __toc = 20501
 apply_patch = <function> defined @CodexLite\patch.lua:52
 UpdateQuestGivers = <function> defined @CodexLite\core.lua:1093
 MapHideNodes = <function> defined @CodexLite\map.lua:1076
 __maxLevel = 70
 SetLargePinSize = <function> defined @CodexLite\map.lua:944
 db = <table> {
 }
 GOSSIP_SHOW = <function> defined @CodexLite\core.lua:1373
 NAME_PLATE_UNIT_REMOVED = <function> defined @CodexLite\init.lua:97
 NAME_PLATE_UNIT_ADDED = <function> defined @CodexLite\init.lua:97
 __ui_setting = CODEX_LITE_SETTING_UI {
 }
 PushAddLine = <function> defined @CodexLite\comm.lua:615
 __PLAYER_ZONE_CHANGED = <function> defined @CodexLite\map.lua:1168
 GetQuestTagInfo = <function> defined @CodexLite\init.lua:852
 core_reset = <function> defined @CodexLite\core.lua:1301
 GROUP_JOINED = <function> defined @CodexLite\comm.lua:791
 map_setup = <function> defined @CodexLite\map.lua:1174
 CoreAddUUID = <function> defined @CodexLite\core.lua:195
 _F_devDebugProfileStart = <function> defined @CodexLite\init.lua:45
 QUEST_DETAIL = <function> defined @CodexLite\core.lua:1417
 CreateSettingUI = <function> defined @CodexLite\setting.lua:270
 DelObject = <function> defined @CodexLite\core.lua:434
 MapDelLargeNodes = <function> defined @CodexLite\map.lua:1029
 DelRefloot = <function> defined @AddOn

**Comment by alexqu0822** [comment]
It is solved in the newer files.  :)
