### ISSUE TITLE
有一个报错

### ISSUE THREAD

**Issue by iwuguo** [alexqu0822/CodexLite#6]
AddOns\CodexLite\core.lua:1254: attempt to index local 'r' (a number value)
Count: 4

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\CodexLite\core.lua"]:1254: in function <AddOns\CodexLite\core.lua:1187>
[string "@AddOns\CodexLite\core.lua"]:1338: in function `func'
[string "@AddOns\CodexLite\init.lua"]:131: in function <AddOns\CodexLite\init.lua:124>

而且只有一个角色报错，删除插件和WTF文件夹都无法解决，好奇怪

**Comment by alexqu0822** [comment]
是的，已经发现这个问题修复了但还没推送。一些自动化的脚本产生的数据格式稍微有点问题

**Comment by iwuguo** [comment]
60怀旧更新1.14版本之后出现错误，无法打开设置界面
AddOns\CodexLite\setting.lua:504: attempt to index field 'mapquestblocked' (a nil value)
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\CodexLite\setting.lua"]:504: in function `setting_setup'
[string "@AddOns\CodexLite\init.lua"]:943: in function <AddOns\CodexLite\init.lua:934>

**Comment by alexqu0822** [comment]
你用的版本似乎有些老

**Comment by iwuguo** [comment]
驱魔师苏利文24885的坐标应该是55.8, 53.8




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexqu0822/CodexLite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 上午9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexqu0822/CodexLite] 有一个报错 (#6)





 
你用的版本似乎有些老
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
